import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import {Header} from "@/components/Header";
import {NextIntlClientProvider} from "next-intl";
import {ReactNode} from "react";
import {setRequestLocale} from "next-intl/server";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "crypto-pulse",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children, params
                                         }: Readonly<{
    children: ReactNode;
    params: Promise<{ locale: "ru" | "en" }>;
}>) {
    const {locale} = await params;

    // Enable static rendering
    setRequestLocale(locale);

    return (
        <html lang={locale} className={'dark'}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <NextIntlClientProvider>
            <Header/>
            {children}
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
